version: 1
applications:
  - appRoot: apps/web-logistician
    frontend:
      phases:
        preBuild:
          commands:
            - npm install -g pnpm@8.15.4
            - cd ../..
            - pnpm install
            - cd packages/contracts && pnpm run build && cd ../..
            - cd packages/utils && pnpm run build && cd ../..
            - cd packages/ui-components
            - echo "Building ui-components..."
            - pnpm run build
            - ls -la dist
            - cd ../..
            - cd apps/web-logistician
        build:
          commands:
            - pnpm run build
            - rm -rf .next
            - echo '{"version":1,"config":{},"appDir":"","files":[],"ignore":[]}' > out/required-server-files.json
      artifacts:
        baseDirectory: out
        files:
          - '**/*'
      cache:
        paths:
          - ../../node_modules/**/*
          - .next/cache/**/*
          - ../../.pnpm-store/**/*
